name: Lint

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check package.json
      run: cat package.json
    - name: Clear npm cache
      run: npm cache clean --force
    - name: Install dependencies
      run: |
        npm install
    - name: Run linters
      run: npm run lint
